#!/bin/bash
#
#
#

metrics=/opt/nce/sonar/metrics
pid=/var/run/sonar.pid
timeout=300
gmond=/etc/ganglia/gmond.conf

function monitor/stop() {
  if test -r "${pid}" ; then
    rm -f "${pid}"
  fi
  exit 1
}
trap monitor/stop INT TERM EXIT

if test -z "$*" ; then
  echo "No sonars defined"
  exit 1
fi

# clean
sonars=""
for s in $* ; do
  sonars=" $(basename $s)"
done

# http://serverfault.com/questions/480371/ipmitool-cant-find-dev-ipmi0-or-dev-ipmidev-0
modprobe ipmi_devintf
modprobe ipmi_si

echo $$ > ${pid}

# main loop
while true ; do
  for s in $sonars ; do
    ${metrics}/${s} $gmond
    sleep 1
  done
  sleep  $timeout &
  wait %1
done
