#!/bin/bash

nagiosStateOk=0
nagiosStateWarning=1
nagiosStateCritical=2
nagiosStateUnknown=3
_exit=$nagiosStateOk

_warn=${1:-30}
_crit=${1:-48}

gstat -1 -i masterhost -a -l | \
grep ^cn | \
awk -v l=${_warn} -F, 'BEGIN{_exit=0} {
sub(/].*/,"",$3);
if ($3 > l ) {
  _exit=1;
}
} END{ exit _exit}'
_exit=$?

gstat -1 -i masterhost -a -l | \
grep ^cn | \
awk -v l=${_crit} -v e=${_exit} -F, 'BEGIN{_exit=e} {
sub(/].*/,"",$3);
if ($3 > l ) {
  _exit=2;
}
} END{ exit _exit}'
_exit=$?

if [ ${_exit} -gt 0 ] ; then
  echo "WARNING: High 15min load on some compute nodes"
  _exit=$nagiosStateWarning
else
  echo "OK: 15 min load is under treshold"
fi

exit ${_exit}
