#!/bin/bash

nagiosStateOk=0
nagiosStateWarning=1
nagiosStateCritical=2
nagiosStateUnknown=3
_exit=$nagiosStateOk

_dead=$(gstat -i scheduler -d | grep Dead | awk '{print $3}')
if [ ${_dead} -gt 0 ] ; then
  # gstat -i scheduler -d
  echo "ERROR: Dead hosts: ${_dead}"
  _exit=$nagiosStateWarning
else
  echo "OK: All hosts are running"
fi

exit ${_exit}
