#!/bin/bash

GPU_COUNT_PER_NODE=2
nagiosStateOk=0
nagiosStateWarning=1
nagiosStateCritical=2
nagiosStateUnknown=3
_exit=$nagiosStateOk

WRONG_NODES=""
for i in {1..44}
do
 (
  node="apollo0"
  if [ $i -lt 10 ];
  then
    node="apollo00"
  fi
  GPUS=`ssh  $node$i 'micsmc -c|grep "Device Utilization"' 2>/dev/null|wc -l`
  echo $node$i $GPUS
 ) & 
done|
{
  while read GPUS
  do
    info=(${GPUS//\n / })
    node=${info[0]}
    GPUS=${info[1]}
    if [[ ( $GPUS -gt 0 )  &&  ($GPUS -ne $GPU_COUNT_PER_NODE ) ]];
    then

      if [ "$WRONG_NODES" == "" ];
      then
        WRONG_NODES="$node"
      else
        WRONG_NODES="$WRONG_NODES, $node"
      fi
    fi
  done

  if [ "$WRONG_NODES" == "" ];
  then
    echo "OK: All Phis are running"
  else
    echo "ERROR: Missing one or more Phi(s) here: $WRONG_NODES"
    _exit=$nagiosStateWarning
  fi

  exit ${_exit}
}
