#!/bin/bash

nagiosStateOk=0
nagiosStateWarning=1
nagiosStateCritical=2
nagiosStateUnknown=3
_exit=$nagiosStateOk

_down=$(scontrol -o show nodes | grep DOWN | wc -l)
if [ ${_down} -gt 0 ] ; then
  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep DOWN
fi


#_drain=$(scontrol -o show nodes | grep DRAIN | wc -l)
#if [ ${_drain} -gt 0 ] ; then
#  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep DRAIN
#fi


_fail=$(scontrol -o show nodes | grep FAIL | wc -l)
if [ ${_fail} -gt 0 ] ; then
  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep FAIL
fi

if [ ${_exit} -gt 0 ] ; then
#  echo "ERROR DOWN: ${_down}  DRAIN: ${_drain}  FAIL: ${_fail}"
  echo "ERROR DOWN: ${_down} FAIL: ${_fail}"
else
  echo "OK: all hosts are running"
fi

exit ${_exit}
