#!/bin/bash

nagiosStateOk=0
nagiosStateWarning=1
nagiosStateCritical=2
nagiosStateUnknown=3
_exit=$nagiosStateOk

_down=$(scontrol -o show nodes | grep DOWN | wc -l)
if [ ${_down} -gt 0 ] ; then
  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep DOWN
fi


_drain=$(sinfo -a | grep drain | awk '{print $4}')
if [ -z "$_drain" ] ; then
  _drain=0
fi
if [ ${_drain} -gt 0 ] ; then
  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep DRAIN
fi


_fail=$(scontrol -o show nodes | grep FAIL | wc -l)
if [ ${_fail} -gt 0 ] ; then
  _exit=$nagiosStateWarning
  # scontrol -o show nodes | grep FAIL
fi

if [ ${_exit} -gt 0 ] ; then
  echo "ERROR DOWN: ${_down}  DRAIN: ${_drain}  FAIL: ${_fail}"
#  echo "ERROR DOWN: ${_down} FAIL: ${_fail}"
  echo "Drained hosts:" `sinfo -a | grep drain | awk '{print $6}'`
  echo "Down hosts: " `sinfo -a | grep down | awk '{print $6}'`
else
  echo "OK: all hosts are running"
fi

exit ${_exit}
