#!/bin/bash

#
# http://superuser.com/questions/368620/should-i-disable-hyperthreading 
#
# run by root before services start
#

echo ""
echo "--- Hyper-threading OFF ---------------------------------"
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | \
sort -u | \
while read sibs ; do
  case "$sibs" in
    *,*)
      oldIFS="$IFS"
      IFS=",$IFS"
      set $sibs
      IFS="$oldIFS"
      shift
      while [ "$1" ]
      do
        echo "Disabling Logical CPU $1 .."
        echo 0 > /sys/devices/system/cpu/cpu$1/online
        shift
      done
    ;;
    *)
    ;;
  esac
done
echo "---------------------------------------------------------"
echo ""
