#!/bin/bash


ssh gpu1 yum -y install slurm-sjobexit.x86_64 slurm-devel.x86_64 slurm-munge.x86_64 \
                       slurm-sjstat.x86_64 slurm-plugins.x86_64 slurm-perlapi.x86_64 \
                       slurm-pam_slurm.x86_64 slurm.x86_64

ssh gpu2 yum -y install slurm-sjobexit.x86_64 slurm-devel.x86_64 slurm-munge.x86_64 \
                       slurm-sjstat.x86_64 slurm-plugins.x86_64 slurm-perlapi.x86_64 \
                       slurm-pam_slurm.x86_64 slurm.x86_64

# ssh gpu1 yum -y update munge
# ssh gpu2 yum -y update munge
