#!/bin/bash

if [ -r "/etc/NCE_SYSTEM" ] && [ `cat /etc/NCE_SYSTEM` == "niif/pecs" ]
then
  nce_dir="/home/opt/nce"
  module_dir="/home/opt/nce/modulefiles"
  package_dir="/home/opt/nce/packages/global"
else
  nce_dir="/opt/nce"
  module_dir="/opt/nce/modulefiles"
  package_dir="/opt/nce/packages/global"
fi

tmp=`mktemp`

cd $nce_dir

# recover deleted files
git checkout $(git ls-files -d) &> /dev/null

# update to the latest repo
git pull

cd $module_dir

for module in `find .`
do
   if [ -d ${module_dir}/${module} ]
   then 
      continue
   fi

   if [ ! -d "${package_dir}/${module}" ]
   then
     echo ${module_dir}/${module} >> $tmp
   fi
done

# delete unnecessary modules
cat $tmp | xargs -i rm {}

rm  $tmp 
