#!/bin/bash

# Source: https://github.com/ganglia/gmetric/blob/master/hpc/sge_jobs/sge_jobs.sh

#adjust for the local environment
source /usr/share/gridengine/default/common/settings.sh

qstat -u \* | awk '
        BEGIN { pending=running=error=0; }
        /^[ 1-9][0-9]/ && ($5 ~ /^qw/)   { pending++; }
        /^[ 1-9][0-9]/ && ($5 ~ /[rRt]/) { running++; }
        /^[ 1-9][0-9]/ && ($5 ~ /E/ )    { error++;   }
    END {
                cmd="/usr/bin/gmetric --name sge_pending --value "pending" --type uint16 --units jobs";
                system(cmd); 
                cmd="/usr/bin/gmetric --name sge_running --value "running" --type uint16 --units jobs";
                system(cmd);
                cmd="/usr/bin/gmetric --name sge_error   --value "error" --type uint16 --units jobs";
                system(cmd);
        }'

